<<<<<<< HEAD
=======
version: 2

>>>>>>> fff18d0f420ca8074563c7aa8c81a99e2146ff7c
sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            data_tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            data_tests:
              - unique
<<<<<<< HEAD
              - not_null
=======
              - not_null
>>>>>>> fff18d0f420ca8074563c7aa8c81a99e2146ff7c
